export const ERROR_CODES = Object.freeze({
  INVALID_COMMAND: 'INVALID_COMMAND',
  INVALID_EVENT: 'INVALID_EVENT',
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  UNKNOWN_COMMAND: 'UNKNOWN_COMMAND',
  STALE_REVISION: 'STALE_REVISION',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
});
